media:
  input: assets/images/project-images
  output: /assets/images/project-images

content:
  - name: projects
    label: Projects
    type: collection
    path: _projects
    fields:
      - name: layout
        label: "Layout"
        type: select
        required: true
        options:
          values:
            [
              { name: project-default, label: "Default project layout" },
              { name: project-gallery, label: "Gallery layout" },
              { name: project-text, label: "Text-only layout" },
            ]

      - { name: featured, label: "Featured", type: boolean }

      - { name: title, label: "Title", type: string, required: true }

      - {
          name: date,
          label: "Date",
          type: date,
          format: YYYY-MM,
          required: true,
        }

      - { name: location, label: "Location", type: string }

      - name: tags
        label: "Tags"
        type: select
        multiple: true
        required: true
        options:
          values:
            - name: architecture
              label: "Architecture"
            - name: landscape-architecture
              label: "Landscape architecture"
            - name: art
              label: "Art"
            - name: photography
              label: "Photography"
            - name: publications
              label: "Publications"
            - name: speaking
              label: "Speaking"
            - name: awarded
              label: "Awarded"

      - name: body
        label: "Description"
        type: rich-text
        options:
          media: false

      - name: images
        label: "Images"
        type: image
        list: true
        options:
          rename: true

      - { name: medium, label: "Medium / Material", type: string }

      - { name: size, label: "Size", type: string }
