media:
  input: assets/images/project-images
  output: /assets/images/project-images

content:
  - name: projects
    label: Projects
    type: collection
    path: _projects
    fields:
      - name: layout
        label: "Choose layout"
        type: select
        required: true
        options:
          values:
            [
              { name: project-default, label: "Default project layout" },
              { name: project-gallery, label: "Gallery layout" },
              { name: project-text, label: "Text-only layout" },
            ]

      - { name: title, label: "Title", type: string, required: true }
      
      - { name: place, label: "Location/organization/firm", type: string }

      - {
          name: date,
          label: "Date",
          type: date,
          required: true,
        }

      - name: body
        label: "Description"
        type: rich-text
        options:
          media: false

      - name: images
        label: "Images"
        type: image
        list: true
        options:
          rename: true

      - { name: featured, label: "Feature on homepage?", type: boolean }
      - name: tags
        label: "Tags"
        type: select
        options:
          multiple: true
          values:
            - name: architecture
              label: "Architecture"
            - name: landscape-architecture
              label: "Landscape architecture"
            - name: art
              label: "Art"
            - name: photography
              label: "Photography"
            - name: publications
              label: "Publications"
            - name: speaking
              label: "Speaking"
            - name: awarded
              label: "Awarded"
