backend:
    name: github
    repo: narita-ico/narita.github.io
    branch: main

media_folder: "assets/images/project-images/{{slug}}"
public_folder: "/assets/images/project-images/{{slug}}"

collections:
    - name: "projects"
      label: "Projects"
      folder: "_projects/"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Project Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Description", name: "body", widget: "markdown" }
          - { label: "Tags", name: "tags", widget: "list" }
          - { label: "Cover Image", name: "image", widget: "image" }
          - {
                label: "Featured",
                name: "featured",
                widget: "boolean",
                default: false,
            }
